project_name: opentelemetry-collector-releases
builds:
    - id: otelcol-contrib
      goos:
        - linux
      goarch:
        - amd64
      dir: distributions/otelcol-contrib/_build
      binary: otelcol-contrib
      ldflags:
        - -s
        - -w
      flags:
        - -trimpath
      env:
        - CGO_ENABLED=0
archives:
    - id: otelcol-contrib
      builds:
        - otelcol-contrib
      name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
nfpms:
    - package_name: otelcol-contrib
      contents:
        - src: distributions/otelcol-contrib/otelcol-contrib.service
          dst: /lib/systemd/system/otelcol-contrib.service
        - src: distributions/otelcol-contrib/otelcol-contrib.conf
          dst: /etc/otelcol-contrib/otelcol-contrib.conf
          type: config|noreplace
        - src: configs/otelcol-contrib.yaml
          dst: /etc/otelcol-contrib/config.yaml
          type: config
      scripts:
        preinstall: distributions/otelcol-contrib/preinstall.sh
        postinstall: distributions/otelcol-contrib/postinstall.sh
        preremove: distributions/otelcol-contrib/preremove.sh
      id: otelcol-contrib
      builds:
        - otelcol-contrib
      formats:
        - deb
      maintainer: The OpenTelemetry Collector maintainers <cncf-opentelemetry-maintainers@lists.cncf.io>
      description: OpenTelemetry Collector - otelcol-contrib
      license: Apache 2.0
checksum:
    name_template: '{{ .ProjectName }}_checksums.txt'
