name: Nsof release builder

on:
  workflow_dispatch:
  push:
    branches: [nsof-*]
    paths:
    - ".goreleaser.yaml"
    - "distributions/otelcol-contrib/manifest.yaml"

jobs:
  build:
    name: Build Debian Package
    strategy:
      matrix:
        GOOS: [linux]
        GOARCH: [amd64]
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '~1.21.1'
          check-latest: true

      - name: Generate the sources
        run: make generate-sources
        env:
          DISTRIBUTIONS: otelcol-contrib

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: --skip-validate --skip-sign --clean --timeout 2h
        env:
          GOOS: ${{ matrix.GOOS }}
          GOARCH: ${{ matrix.GOARCH }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v3
        with:
          name: all-artifacts
          path: dist/*/*
